### ISSUE TITLE
Missing Wiki page "How to use this SteamBot for CSGOWINBIG"

### ISSUE THREAD

**Issue by mistermoule** [ztizzlegaming/CSGOWinBig#191]
The following wikipage is missing: https://github.com/TheAnthonyNL/SteamBot/wiki/How-to-use-this-SteamBot-for-CSGOWINBIG

**Comment by TheAnthonyNL** [comment]
Yes i removed it because i got tired of the people lacking reading skills. 

- compile it on windows
- set the settings
- then write exec 0 linkauth
- input 0 steamguard-code
- input 0 phonenumber
- input 0 smscode
- aka follow the onscreen info
- but you have to do it on windows
- cause on linux it will fail

simple as that.

**Comment by scorpionofwar** [comment]
And how to let the bot send the items to the admin account?

**Comment by irgredneck** [comment]
@TheAnthonyNL Do you have to do anything so it'll talk to the website, like confirm that items were deposited by a user?

**Comment by mibac138** [comment]
@TheAnthonyNL I tried it but it says: "ERROR: Error linking authenticator: BadSMSCode". Even though I tried it 2 times and I'm sure codes are right. Please help!

**Comment by irgredneck** [comment]
@mibac138 I had this issue too, found out I was on the wrong version of SteamKit. Check the version (in the package manager), you should be on 1.6.2 I believe

**Comment by mibac138** [comment]
@irgredneck Unfortunately changing version didn't help. Maybe it's something with protobuf's version?

**Comment by Fusionn** [comment]
Anyone having issues with the authentication, add the phonenumber on steam manually and then go through the auth steps.

Source: https://github.com/geel9/SteamAuth/issues/32
