### ISSUE TITLE
Infinite 'loading...'

### ISSUE THREAD

**Issue by M60Warrior** [ztizzlegaming/CSGOWinBig#6]
The current pot items and chat box both are stuck on 'loading…'
I've made sure that the database connection is correct and the bot is online. It just wont get off of loading..

**Comment by ztizzlegaming** [comment]
You are probably getting some sort of JavaScript error from something. If you are using Chrome, go here:

![](https://i.gyazo.com/3d9715e865f617454cbfe08d996086ac.png)

and the JavaScript console will pop up. From here, you will be able to see if there are any JS errors.

**Comment by M60Warrior** [comment]
Sorry I forgot to say what I've already done. I've checked the console to see if there are any errors, Checked the DB connection, and I've freshly downloaded and installed the source on the server.

**Comment by Dreburwar** [comment]
Same here..

**Comment by ztizzlegaming** [comment]
Alright if you aren't getting any JavaScript errors, try going directly to the /php/login-status.php file on your server in your browser. What I suspect is either you don't have the passwords.txt file setup, or it is somehow setup incorrectly.

**Comment by M60Warrior** [comment]
I think it might be the passwords.txt isn't setup properly for me. I tried navigating to /php/login-status.php in my browser and it gave me an error. 

"Fatal error: Uncaught exception 'PDOException' with message ' in C:\wamp\www\php\default.php on line 21"

I have my passwords.txt setup correctly but and in C:\wamp is that not correct?

**Comment by ztizzlegaming** [comment]
Oh well the passwords file is probably fine, I believe you are getting an error when trying to access your database. Because you are running this on your own wamp server, you may not have the PDO driver installed, take a look at these:

http://forum.wampserver.com/read.php?2,18597,18597

http://stackoverflow.com/questions/10155624/how-do-i-get-pdo-to-work-on-wamp-with-php-5-4

I have never really used wamp, I have always just used other hosting, for example, right now I am using bluehost to host my site, so I am not sure how much help I can be with this issue. You migut just want to google around and see what you can find. Good luck!

**Comment by M60Warrior** [comment]
Thanks for the info. I have PDO installed and the site was working fine a few days ago (Depositing, no 'loading...', etc) I don't know what happened but it just quit working. I'll try to upload the files to hosting site and check out and see if it is working there.
